2018-07-25 15:37:56,661:ERROR:HTTPConnectionPool(host='172.104.49.91', port=4984): Max retries exceeded with url: /awhcurisdb010832/_all_docs?access=false&channels=false&include_docs=true&revs=false&update_seq=false&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d274d68>: Failed to establish a new connection: [Errno 51] Network is unreachable',))
2018-07-25 15:37:56,671:ERROR:<RC=0x31[The remote host was unreachable - is your network OK?], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,1066)>
2018-07-25 15:41:31,801:ERROR:<RC=0x17[Client-Side timeout exceeded for operation. Inspect network conditions or increase the timeout], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,1066)>
2018-07-25 15:41:52,919:ERROR:HTTPConnectionPool(host='172.104.49.91', port=4984): Max retries exceeded with url: /awhcurisdb010832/_all_docs?access=false&channels=false&include_docs=true&revs=false&update_seq=false&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e971d30>: Failed to establish a new connection: [Errno 51] Network is unreachable',))
2018-07-25 15:41:52,922:ERROR:<RC=0x31[The remote host was unreachable - is your network OK?], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,1066)>
2018-07-25 15:43:35,953:ERROR:HTTPConnectionPool(host='172.104.49.91', port=4984): Max retries exceeded with url: /awhcurisdb010832/_all_docs?access=false&channels=false&include_docs=true&revs=false&update_seq=false&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107be2d30>: Failed to establish a new connection: [Errno 51] Network is unreachable',))
2018-07-25 15:43:35,962:ERROR:<RC=0x31[The remote host was unreachable - is your network OK?], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,1066)>
